name: Deployment (Container)

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container: node:16
    env:
      CACHE_KEY: node-deps
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 27017
    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        ports:
          - 27017:27017
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          cd jobDocker
          npm ci

      - name: Run server
        run: |
          cd jobDocker
          npm start & npx wait-on http://mongodb:$PORT

      - name: Run tests
        run: |
          cd jobDocker
          npm test

      - name: Output information
        run: |
          cd jobDocker
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      MONGODB_DB_NAME: gha-demo
    steps:
      - name: Output information
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
