name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [10, 14, 16] #
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          cd jobExecution
          npm install
      - name: Build Project
        run: |
          cd jobExecution
          npm run build
