name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo ${{ toJSON(github) }} # Outputs information about the GitHub context
